channels:
  - conda-forge
  - bioconda
dependencies:
  - bioconda::snakemake-minimal =5.4.5
  - python =3.6
  - jinja2 =2.10
  - networkx =2.1
  - matplotlib =2.2.3
  - graphviz =2.38.0
  - bcftools =1.9
  - samtools =1.9
  - bwa =0.7.17
  - pysam =0.15.0
  - spades =3.14.0
  - pilon =1.22
  - bbmap =37.78
  - subread =2.0.1
  - fastqc = 0.11.8
  - star = 2.7.5a
  - trimmomatic = 0.38

